{% set name = "retropath2_wrapper" %}
{% set version = "3.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/retropath2-wrapper/archive/{{ version }}.tar.gz
  sha256: 29207e3cc92d8d3941b74d3f8261bc52ea5c7d3d17428328160e9bd5b3f0eca3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - brs_utils >=1.23.1
    - filetype
    - colored
    - freetype
    - nss-cos7-x86_64
    - atk-devel-cos7-x86_64
    - cups-devel-cos7-x86_64
    - xorg-libxcomposite
    - xorg-libxdamage
    - xorg-libxrandr
    - libxkbcommon-devel-cos7-x86_64
    - alsa-lib-devel-cos7-x86_64
    - libxshmfence-devel-cos7-x86_64
    - mesa-libgbm-cos7-x86_64
    - libdrm-cos7-x86_64

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -m {{ name|lower }} --help
    - python -m pytest tests

about:
  home: https://github.com/brsynth/retropath2-wrapper
  summary: Python wrapper to run RetroPath2.0 KNIME workflow
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - guillaume-gricourt
    - breakthewall
