{% set name = "retropath2_wrapper" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/retropath2-wrapper/archive/{{ version }}.tar.gz
  sha256: 63a141423932d25a734c59e782d04dc9e30bd3d7b43cc0d4bf8eb43173b1cf40

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - brs_utils >=1.19
    - filetype
    - colored
    - freetype
    - nss-cos7-x86_64
    - atk-devel-cos7-x86_64
    - cups-devel-cos7-x86_64
    - xorg-libxcomposite
    - xorg-libxdamage
    - xorg-libxrandr
    - libxkbcommon-devel-cos7-x86_64
    - alsa-lib-devel-cos7-x86_64
    - libxshmfence-devel-cos7-x86_64
    - mesa-libgbm-cos7-x86_64
    - libdrm-cos7-x86_64

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - python -m pytest tests

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: Python wrapper to run RetroPath2.0 KNIME workflow
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - guillaume-gricourt
    - breakthewall
    - kenza12
    - guillaume-gricourt
